### ISSUE TITLE
[6.x] Handle `OAuthException` by default but allow override in AppServiceProvider

### ISSUE THREAD

**Issue by JamesFreeman** [webfox/laravel-xero-oauth2#110]
At the moment, users are required to register the exception handler in their service providers, it would be a nice default if we could register a nice default, if they want to override it they can.

**Comment by JamesFreeman** [comment]
I don't know the best way of implementing this. Ideally I'd like the package to listen for the `OAuthException` and redirect as per the example in the readme by default. Which would stop users from being forced to register an exception listener in their bootstrap. Users will still need to be able to listen to the event, and change the default behaviour if they choose. 

Any thoughts?

@hailwood @joe-niland

**Comment by joe-niland** [comment]
@JamesFreeman thanks for raising this - I'm keen to come up with the ideal solution.

First of all, however, I'm a bit confused because prior to the change (4.4.0), the behaviour on clicking Cancel on the Xero authorisation page was to fail the validation due to the missing `code` parameter.

This would then call `AuthorizationCallbackController::onFailure()` which simply raises the exception.

So the end result is that the package throws a ValidationException. The default behaviour in Laravel for validation errors is to redirect to the address specified in the request's Referer header. In this case it redirects to https://authorize.xero.com/

I guess what I'm saying is I don't see how the existing/default behaviour is useful since it doesn't benefit the user in any way.

Could you please clarify which example in the README you mean?

Without thinking it through fully, one way we could do it is modify the config to include a redirect for 'xero.auth.failure' and then modify `onFailure()` to send the error details to this route. This still requires the user to define the route though. I am not too sure what a reasonable default could be because every app will use this package differently.

Please let me know your thoughts!

**Comment by JamesFreeman** [comment]
I agree the default behaviour before the fix was wrong and not ideal - so something is needed. 

For instance, when I upgraded from v4 to v5, I was forced to register this exception with my app code. I was hoping we would be able to avoid users being forced to install to get a successful (non 500) response.

<img width="880" alt="Screenshot 2024-09-13 at 08 13 52" src="https://github.com/user-attachments/assets/2fc94523-99b3-4f73-a90c-a1f390a456fe">

I was wondering if we could in some way register our exception handler for `OAuthException`, which would in turn redirect to a failure page of some kind.

Not sure on the best behaviour is.

**Comment by hailwood** [comment]
The more I think about this, and especially in context of all the great work @JamesFreeman has done for version 6, the more I'm convinced that we *shouldn't* be handling this automatically. Instead, we should just make it easy for users to handle it where they're configuring the rest of the package.

In version six we've got our `Xero` class for configuring the package.
I believe now we're always throwing an exception that extends [the base XeroException](https://github.com/webfox/laravel-xero-oauth2/blob/develop/src/Exceptions/XeroException.php).

So we could add a `renderExceptionsUsing` and `reportExceptionsUsing` method for the user — users would do something like 
```php
Xero::renderExceptionsUsing(fn(XeroException $e) => redirect()->route('some.user.defined.route')
  ->with('reason', match (true) {
    $e instanceof OauthException     => 'oauth',
    $e instanceof XeroTenantNotFound => 'missing_tenant',
    default                          => 'generic'
  })
);

Xero::reportExceptionsUsing(fn(XeroException $e) => match (true) {
  $e instanceof OauthException          => null,
  $e instanceof XeroCredentialsNotFound => null,
  default                               => true
});
```

Behind the scenes, we'd just add a `render` and `report` method to our base exception that checks whether the handler has been defined, if it has, we'll call and return that, if it hasn't, we'll return false, so Laravel does its default behaviour.

What are your thoughts @JamesFreeman / @joe-niland?

**Comment by JamesFreeman** [comment]
I agree, I think we should leave it as @joe-niland originally proposed it. Users can either choose to handle the exception or leave it as a 500 - As Joe had mentioned they would have got a non-200 response before. 

I did have a look around at Spatie for some inspiration to see if there were any improvements we could make it looks like the end users have to handle the exceptions in their apps without a default. 

(See here: https://github.com/spatie/laravel-multitenancy/blob/92188aa175c37629af46386b302691cfade5332a/docs/advanced-usage/ensuring-a-current-tenant-has-been-set.md?plain=1#L34)

I have also noticed this is how they handle the "message" part of the exception by calling a static method on the Exception which has the hardcoded error messages: 

https://github.com/spatie/laravel-multitenancy/blob/92188aa175c37629af46386b302691cfade5332a/src/Exceptions/NoCurrentTenant.php

That being said, I'm happy for this ticket to be closed or handled via the `Xero` class - How'd you want to proceed @hailwood?

**Comment by hailwood** [comment]
Yeah, Spatie like their factories 😅
I don't have a preference for or against them.

Let's keep it simple for now and ensure that we throw the right exceptions on an OAuth error and make sure we guide the users to add an exception handler and call it a day.
We'll document all the exceptions the package may throw and when it might throw them.

We can revisit this if it still causes issues for users 👍

**Comment by joe-niland** [comment]
@hailwood @JamesFreeman thank you for working through this. Apologies for the delayed response.

I'm about to do a bit more dev using this package so I will have a go at documenting the exceptions.
