### ISSUE TITLE
Upgrade to use the latest version of XeroAPI / xero-php-oauth2 

### ISSUE THREAD

**Issue by plexus77** [webfox/laravel-xero-oauth2#16]
Hi there, I noticed that the package is currently using XeroAPI / xero-php-oauth2  1.2.1

Any plans on upgrading to use V 2.

Thanks for the great work PS

**Comment by hailwood** [comment]
Hi @plexus77 
I'm currently investigating adding tests to this package to ensure we don't break anything, though I'm currently unsure if that's possible since a test would require talking with the xero api.

Either way I should have an update available this weekend with the latest version of the xero api 🙂

**Comment by hailwood** [comment]
Hi @plexus77 v 1.3.0 has just been released with support for the updated Xero api.
There are no breaking changes.

**Comment by plexus77** [comment]
Thanks you @hailwood :)
