### ISSUE TITLE
BatchPayment delete

### ISSUE THREAD

**Issue by macorera** [webfox/laravel-xero-oauth2#30]
Hi,

I want to delete batch payment via this package. There is no method to deleteBatchPayment.

**Comment by hailwood** [comment]
Hi, thanks for using our package and submitting an issue!

It looks like this issue is in relation to a specific usage of the API rather than just connecting to it, 
This package is simply a bridge that deals with the Oauth connections in a Laravel app. Once you've got the connection up and running you're just using the official framework-agnostic api SDK provided by Xero.

This question would be better suited to ask over on [that repository instead](https://github.com/XeroAPI/xero-php-oauth2/issues/new/choose)!


Good luck!
