### ISSUE TITLE
Documentation:  including xero oauth in a php cron job

### ISSUE THREAD

**Issue by helloadmin** [webfox/laravel-xero-oauth2#64]
I suspect there are a lot of people (including me) that want to push transactions into Xero for billing purposes on a scheduled basis.  For Laravel, this means the scheduler and commands and no ui.

It would be super helpful to have a paragraph or two in the readme on how you recommend using laravel-xero-oauth2 within a scheduled command where its triggered via cron and doesn't have someone to type xero credentials into a oauth web page.  There seems to be a lot of posts online with some ideas but I have found none that talk about using your library.  Most talk about a custom implementation and guzzle.

Awesome library. Thanks for the work and for making it public.

Cheers,

**Comment by TheWayneSwart** [comment]
I would like to add to this. Trying to interact with the Xero API from the CLI results in the following error:

`Return value of Webfox\Xero\Oauth2CredentialManagers\FileStore::getRefreshToken() must be of the type string, null returned`

From a browser it all works fine, as expected. I don't mind having to authenticate my app once in order to get an access token but I need to be able to schedule my invoices from CLI.

**Comment by stevethomas** [comment]
Not sure if i'm understanding properly, but https://github.com/webfox/laravel-xero-oauth2/pull/67 / v3 allowed me to access the Xero API from scheduled commands just fine, now that the credentials moved to a cloud disk.

Previously this wasn't working because my web requests and scheduled commands were running on different servers and the filesystem was hardcoded to the local disk. Using CacheStore also seemed unreliable.

I ran the OAuth flow once from the web app and then any command can access the credentials in the JSON file.
