### ISSUE TITLE
Log out from Xero?

### ISSUE THREAD

**Issue by musiwei** [webfox/laravel-xero-oauth2#65]
This may seem obvious but there is no 'log out from Xero'. 

I understand it is as simple as removing the JSON file, but adding a route and a function is all we need.

**Comment by hailwood** [comment]
Happy to accept a PR to add a method to the credential managers to delete the credentials.
I don't think we'll automatically add a route though as we have no way of knowing what a user would expect after logging out of Xero.

**Comment by jolora** [comment]
Sorry to pick up a closed issue but just to expand... I don't think it's enough to just delete the credentials. Because if you attempt to reconnect with the same account you deleted credentials for you'll find that account is disabled in the "already connected" section of the account list -- so cannot reconnect.

The method would also need to somehow inform Xero that the account is no longer connected to the app.

**Comment by craigrileyuk** [comment]
For anyone searching for this:

```php
    public function disconnect(IdentityApi $api, OauthCredentialManager $xeroCredentials)
    {
        $tenants = $xeroCredentials->getTenants();

        foreach ($tenants as $tenant) {
            $api->deleteConnection($tenant['ConnectionId']);
        }

        if ($xeroCredentials instanceof FileStore) {
            $disk = app(FilesystemManager::class)->disk(config('xero.credential_disk', config('filesystems.default')));
            $disk->delete('xero.json');
        }

        return back();
    }
```

is how we handle completely destroying a connection to Xero.

The CredentialManager interface doesn't seem to have a method for destroying the data source (only a store method which requires a new AccessToken to save over the top) so we went a bit custom on deleting the JSON file.
