### ISSUE TITLE
How to store multiple tenants?

### ISSUE THREAD

**Issue by tonypartridge** [webfox/laravel-xero-oauth2#69]
The connection works great and is simple out of the box, we can connect and select multiple tenants but the store only stores 1 tenant, the last one selected. 

So how do we store all selected tenants so we can get the tenant id in a model selection for instance?

**Comment by tony-riela** [comment]
Anyone?

**Comment by AllanGallop** [comment]
@tonypartridge 
I have similar requirement, and ended up making some changes to OauthCredentialManager and related Storage services to store tenant ID and Name as an array instead of the first returned orgs TenantID . It's on a [fork](https://github.com/AllanGallop/laravel-xero-oauth2-multi-tenant) currently if you want an example

**Comment by AllanGallop** [comment]
> @AllanGallop looking over your fork, I'd be happy to merge that in if you opened a PR :)

Awesome, I'll branch and do so

**Comment by hailwood** [comment]
4.0.0 Release
